stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew assemble --no-daemon

test:
  stage: test
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport --no-daemon
  artifacts:
    paths:
      - backend/build/reports/jacoco/test/jacocoTestReport.xml

sonarqube:
  stage: sonarqube
  variables:
    SONAR_HOST_URL: "http://localhost:9000"
    SONAR_TOKEN: "$SONAR_TOKEN"
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew sonar
  dependencies:
    - test