stages:
  - build
  - test
  - sonarqube
  - package
  - trigger-infra

build:
  stage: build
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew assemble --no-daemon

test:
  stage: test
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport --no-daemon
  artifacts:
    paths:
      - backend/build/reports/jacoco/test/jacocoTestReport.xml

sonarqube:
  stage: sonarqube
  variables:
    SONAR_HOST_URL: "http://145.220.72.104:9000"
    SONAR_TOKEN: "$SONAR_TOKEN"
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew sonar
  dependencies:
    - test

build-and-push-docker-image:
  stage: package
  script:
    - sudo chmod 666 /var/run/docker.sock
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - cd backend
    - docker build -t claracahyanintyas/flashcards-backend:latest .
    - docker push claracahyanintyas/flashcards-backend:latest
  only:
    - main

trigger-infra-docker:
  stage: trigger-infra
  trigger:
    project: I545577/flash-cards-infra
    branch: main
    strategy: depend
  variables:
    TRIGGERED_BY: "backend"
    APP_COMMIT_SHA: $CI_COMMIT_SHA
  only:
    - main