spring.datasource.url=jdbc:postgresql://localhost:5433/flashcards_test
spring.datasource.username=testuser
spring.datasource.password=testpass


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.autocommit=false
