spring.datasource.url=jdbc:postgresql://145.220.72.104:5432/your_database_name
spring.datasource.username=testuser
spring.datasource.password=testpass


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.autocommit=false
